version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: feed_mongo
    restart: unless-stopped
    secrets:
      - mongo_username
      - mongo_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_INITDB_DATABASE: feeddb
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_init:/docker-entrypoint-initdb.d:ro
    networks:
      - feed_network

  # Commented out until ready for containerization
  # feed_processor:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: feed_processor
  #   restart: unless-stopped
  #   depends_on:
  #     - mongodb
  #   secrets:
  #     - feedly_token
  #     - openai_api_key
  #     - github_token
  #   environment:
  #     - MONGODB_HOST=mongodb
  #     - MONGODB_PORT=27017
  #     - MONGODB_USERNAME_FILE=/run/secrets/mongo_username
  #     - MONGODB_PASSWORD_FILE=/run/secrets/mongo_password
  #     - FEEDLY_TOKEN_FILE=/run/secrets/feedly_token
  #     - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
  #     - GITHUB_TOKEN_FILE=/run/secrets/github_token
  #   volumes:
  #     - ../config:/app/config:ro
  #     - ../output:/app/output
  #   networks:
  #     - feed_network

networks:
  feed_network:
    driver: bridge

volumes:
  mongodb_data:

secrets:
  mongo_username:
    file: ./secrets/mongo_username.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
  feedly_token:
    file: ./secrets/feedly_token.txt
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  github_token:
    file: ./secrets/github_token.txt
